# Generated by Django 3.1 on 2021-03-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210304_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivereAt',
            new_name='deliveredAt',
        ),
    ]
